# Generated by Django 4.2.7 on 2023-12-07 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coupon_code', models.CharField(max_length=10, unique=True)),
                ('description', models.CharField(max_length=50)),
                ('dis_percentage', models.DecimalField(decimal_places=1, max_digits=3)),
                ('min_amount', models.PositiveIntegerField(default=500)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expiry_date', models.DateField()),
            ],
            options={
                'db_table': 'coupon',
            },
        ),
    ]
