# Generated by Django 4.2.7 on 2023-12-29 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('offer_manage', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='brandoffer',
            old_name='offer_expire',
            new_name='offer_expire_date',
        ),
        migrations.RenameField(
            model_name='categoryoffer',
            old_name='offer_expire',
            new_name='offer_expire_date',
        ),
    ]
