# Generated by Django 4.2.7 on 2023-12-03 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('CASH ON DELVIVERY', 'Cash on delivery'), ('PROCESSING', 'Processing'), ('DISPATCHED', 'Dispatched'), ('OUT OF DELIVERY', 'Out of delivery'), ('CANCELLED', 'Cancelled'), ('RETURNED', 'Returned')], default='New', max_length=20),
        ),
    ]
