# Generated by Django 4.2.7 on 2023-12-03 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_remove_order_additional_information_order_shipping_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='total_discount',
            new_name='sub_total',
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('CASH ON DELVIVERY', 'Cash on delivery'), ('PROCESSING', 'Processing'), ('DISPATCHED', 'Dispatched'), ('OUT OF DELIVERY', 'Out of delivery'), ('CANCELLED', 'Cancelled'), ('RETURNED', 'Returned')], default='Processing', max_length=20),
        ),
    ]
