# Generated by Django 4.2.7 on 2023-12-03 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_rename_total_discount_order_sub_total_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('PROCESSING', 'Processing'), ('DISPATCHED', 'Dispatched'), ('OUT OF DELIVERY', 'Out of delivery'), ('CANCELLED', 'Cancelled'), ('RETURNED', 'Returned')], default='Processing', max_length=20),
        ),
    ]
