# Generated by Django 4.2.7 on 2023-12-10 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0008_payment_payment_signature_alter_order_order_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_no',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
