# Generated by Django 4.2.7 on 2023-12-11 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0010_alter_payment_amount_paid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('PROCESSING', 'Processing'), ('DISPATCHED', 'Dispatched'), ('OUT FOR DELIVERY', 'Out for delivery'), ('CANCELLED', 'Cancelled'), ('RETURNED', 'Returned'), ('DELIVERED', 'Delivered')], default='PROCESSING', max_length=20),
        ),
    ]
