# Generated by Django 4.2.7 on 2023-12-15 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0012_orderproduct_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='status',
        ),
    ]
