# Generated by Django 4.2.7 on 2023-12-15 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0015_remove_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderproduct',
            name='status',
            field=models.CharField(choices=[('CANCELLED', 'Cancelled'), ('RETURNED', 'Returned'), ('DELIVERED', 'Delivered')], default='PROCESSING', max_length=20),
        ),
    ]
