# Generated by Django 4.2.7 on 2023-12-16 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0018_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderproduct',
            name='status',
            field=models.CharField(choices=[('CANCELLED', 'Cancelled'), ('RETURNED', 'Returned'), ('SUCCESS', 'Success')], default='SUCCESS', max_length=20),
        ),
    ]
