# Generated by Django 4.2.7 on 2023-12-18 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0021_remove_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='wallet_amount',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
