# Generated by Django 4.2.7 on 2023-12-01 12:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_address_address_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='phone',
            field=models.BigIntegerField(null=True, unique=True, validators=[django.core.validators.MinValueValidator(1000000000), django.core.validators.MaxValueValidator(9999999999)]),
        ),
    ]
