# Generated by Django 4.2.7 on 2023-12-05 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_alter_address_address_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='created_At',
            field=models.DateField(default='2023-12-02'),
        ),
    ]
