# Generated by Django 4.2.7 on 2023-12-05 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_address_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='created_At',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
