# Generated by Django 4.2.7 on 2023-12-06 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_rename_created_at_address_created_at'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='address',
            table='address',
        ),
    ]
