# Generated by Django 4.2.7 on 2023-12-06 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_alter_address_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='address',
            table=None,
        ),
    ]
