# Generated by Django 4.2.7 on 2023-11-09 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pro_category', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categories',
            name='category_title',
            field=models.CharField(max_length=40, unique=True),
        ),
    ]
