# Generated by Django 4.2.7 on 2023-11-09 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pro_category', '0002_alter_categories_category_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categories',
            name='brand',
        ),
    ]
