# Generated by Django 4.2.7 on 2023-11-09 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pro_category', '0003_remove_categories_brand'),
    ]

    operations = [
        migrations.AddField(
            model_name='categories',
            name='category_img',
            field=models.ImageField(default='', upload_to='category/'),
        ),
        migrations.AlterField(
            model_name='categories',
            name='category_title',
            field=models.CharField(default='', max_length=40, unique=True),
        ),
        migrations.AlterField(
            model_name='categories',
            name='description',
            field=models.CharField(default='', max_length=250),
        ),
    ]
