# Generated by Django 4.2.7 on 2023-12-13 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_side', '0019_alter_user_date_of_birth'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='user_name',
            new_name='username',
        ),
    ]
