# Generated by Django 4.2.7 on 2023-11-11 10:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='attribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('atrribute_name', models.CharField(max_length=50, unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.RenameField(
            model_name='product_varient',
            old_name='product_id',
            new_name='product_name',
        ),
        migrations.RemoveField(
            model_name='product_varient',
            name='product_color',
        ),
        migrations.AddField(
            model_name='brand',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='product',
            name='product_slug',
            field=models.SlugField(blank=True, max_length=300, unique=True),
        ),
        migrations.AddField(
            model_name='product_varient',
            name='thumbnail_image',
            field=models.ImageField(blank=True, upload_to='product/thumbnail'),
        ),
        migrations.AddField(
            model_name='product_varient',
            name='varient_slug',
            field=models.SlugField(blank=True, max_length=300, unique=True),
        ),
        migrations.AlterField(
            model_name='product_image',
            name='image',
            field=models.ImageField(upload_to='varient/'),
        ),
        migrations.CreateModel(
            name='attribute_values',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attribute_value', models.CharField(max_length=40)),
                ('attribute_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.attribute')),
            ],
        ),
        migrations.AddField(
            model_name='product_varient',
            name='attribute_name',
            field=models.ManyToManyField(max_length=100, to='product.attribute'),
        ),
    ]
