# Generated by Django 4.2.7 on 2023-11-13 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_alter_brand_brand_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attribute_values',
            old_name='attribute_name',
            new_name='attribute',
        ),
    ]
