# Generated by Django 4.2.7 on 2023-11-13 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_rename_attribute_name_attribute_values_attribute'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attribute_values',
            old_name='attribute',
            new_name='attribute_id',
        ),
    ]
