# Generated by Django 4.2.7 on 2023-11-13 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_rename_attribute_attribute_values_attribute_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='attribute_values',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='attribute_values',
            name='attribute_value',
            field=models.CharField(max_length=40, unique=True),
        ),
    ]
