# Generated by Django 4.2.7 on 2023-11-15 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_attribute_values_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_varient',
            name='sku_id',
            field=models.CharField(default='', max_length=30, unique=True),
        ),
        migrations.AddField(
            model_name='product_varient',
            name='stock',
            field=models.IntegerField(default=0),
        ),
    ]
