# Generated by Django 4.2.5 on 2023-11-16 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_product_varient_sku_id_product_varient_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_varient',
            name='attribute_name',
            field=models.ManyToManyField(max_length=100, to='product.attribute_values'),
        ),
    ]
