# Generated by Django 4.2.7 on 2023-11-20 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_alter_product_product_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attribute_values',
            old_name='is_active',
            new_name='attr_is_active',
        ),
        migrations.RenameField(
            model_name='product_varient',
            old_name='is_active',
            new_name='vari_is_active',
        ),
    ]
