# Generated by Django 4.2.7 on 2023-11-27 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_rename_is_active_attribute_values_attr_is_active_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product_varient',
            old_name='discount_price',
            new_name='discount_percentage',
        ),
    ]
