# Generated by Django 4.2.7 on 2023-11-27 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0012_rename_discount_price_product_varient_discount_percentage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_varient',
            name='discount_percentage',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
