# Generated by Django 4.2.7 on 2023-12-11 17:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0013_alter_product_varient_discount_percentage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_varient',
            name='product_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_vareint', to='product.product'),
        ),
    ]
